version: '2'

services:
  app-customer:
    image: 'danie/customer:1.0.0-SNAPSHOT'
    build:
      context: .
    container_name: app-customer
    depends_on: 
      - db-customer
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db-customer:5434/customerdb
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=admin
      - QUARKUS_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8083:8083
    networks:
      - docker-db-test

  db-customer:
    image: 'postgres:latest'
    container_name: db-customer
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customerdb
    networks:
      - docker-db-test

networks:
  docker-db-test:
    external: true
    name: docker-db-test
